######################################################################
# Automatically generated by qmake (3.0) ??? ?? 20 09:23:33 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = qtmess
INCLUDEPATH += .

# Input
SOURCES += qtmess.cpp
